logging:
  level:
    org.innovds: trace
    
server:
  error:
    include-stacktrace: on-trace-param

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
